### PR TITLE
Statistics Service

### PR DESCRIPTION
**Pull request by dragica**

### CODE REVIEW

**Comment by despotovska** [comment]
The time format  h + ' hours ' + m + ' min ' + s + ' sec' shouldn't be in English. You should take into consideration that in the Component it will be implemented with ng2-translate so you should for example return an object with 3 props: hours, minutes and seconds.

The 'not applicable' case should be validated in the api and I think it should be removed from the service.

**Comment by dnoveska** [comment]
- 1

**Comment by eljesaz** [comment]
+1

**Comment by despotovska** [comment]
+1

**Pull request merged**
