### PR TITLE
Renamed Filters to Pipes and deleted unnecessary Users class

### PR DESCRIPTION
**Pull request by despotovska**

### CODE REVIEW

**Comment by ebarabanovska** [comment]
+1

**Comment by sumarsky** [comment]
The component name is great, Filter should be changed with Pipe.
I strongly disagree with the Pipe suffix in the selector.
Take this as example https://angular.io/docs/ts/latest/api/#!?apiFilter=pipe

AsyncPipe is the component while the selector is only 'async'
DatePipe is the component while the selector is only 'date'
JsonPipe is the component while the selector is only 'json'

**Comment by despotovska** [comment]
@sumarsky I completely agree with you, I just renamed it everywhere I found 'filter'. I will remove the suffix now.

**Comment by eljesaz** [comment]
+1

**Comment by dragica** [comment]
+1

**Pull request merged**
