### PR TITLE
OnLauncherClosed => close any running game

### PR DESCRIPTION
**Pull request by sumarsky**
api/terminateGameProcess: as we already have a handler to the child_process, we can easily kill the process when the Launcher app is closed. "taskkill /PID"

### CODE REVIEW

**Comment by dnoveska** [comment]
Koga sme kaj iminjata, malce e brutalno e taskkill :) Inaku logikata na kodot mi e ok: +1 :)

**Comment by despotovska** [comment]
+1

**Comment by sumarsky** [comment]
@dnoveska не е тоа мој код, тоа е од Microsoft :) мојот код е "api/terminateGameProcess"

https://technet.microsoft.com/en-us/library/bb491009.aspx

**Comment by dnoveska** [comment]
@sumarsky microsoft imale los den koga go krstile taskkill :)

**Comment by ebarabanovska** [comment]
+1

**Pull request merged**
