### PR TITLE
UploadPicture preview added.

### PR DESCRIPTION
**Pull request by taurusmk**
e2e tests will be added from Josif after merging the code. Position of the picture will be discussed with other team members.

### CODE REVIEW

**Comment by eljesaz** [comment]
+1

**Comment by sumarsky** [comment]
+1

**Comment by despotovska** [comment]
We agreed that the picture preview should appear where the label 'Слика' is located. As I can see from the html it is under the input. Correct me if I'm wrong. @taurusmk @dragica

**Comment by taurusmk** [comment]
What "where the label 'Слика' is located" means, left or right from 'Слика' or above/below? We tried many positions and none looked good, so we decided to discuss with other TM to redesign the whole page.

**Comment by despotovska** [comment]
OK. It's fine by me, I just wanted to remind you.
+1

**Pull request merged**
