### PR TITLE
Added input devices in UserSettings component

### PR DESCRIPTION
**Pull request by ebarabanovska**
-  Added input devices in UserSettings and Register component.
-  Extended UserSettingsService with device type.
-  Added ids on input devices radioButtons list for the need of e2e tests.

### CODE REVIEW

**Comment by despotovska** [comment]
@ebarabanovska Why do you pass this argument **-dt** to to the cause and effect jar file?

**Comment by ebarabanovska** [comment]
Yes @despotovska  I can agree with you, there is no need of passing the **-dt** argument to the "cause and effect" jar file, because input device types are not implemented for passing to this game.

**Comment by eljesaz** [comment]
+1

**Comment by despotovska** [comment]
+1

**Comment by dragica** [comment]
+1

**Pull request merged**
